### ISSUE TITLE
Restart?

### ISSUE THREAD

**Issue by Olamyy** [python-recsys/crab#20]
Hi,
Is this package actively being maintained?
If it's not, I'm looking to start something similar using the structure available. 
Can I go ahead?

**Comment by lucduff** [comment]
Hi! Olamyy

The project is dormant. You can use whatever you need. I am happy my project is a source of inspiration for something better.

All the best!

Cheers, L

**Comment by Olamyy** [comment]
Alright. Thanks. I'd once in a while pop in here if I need help with something. Hopefully you can help out.
